{% set name = "gdown" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f1f735a174ef3599fca95786aafac1219b9d85d4c729ccb95e674996c47fd44

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gdown = gdown.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - filelock
    - requests
    - tqdm
    - beautifulsoup4

test:
  requires:
    - python {{ python_min }}
  imports:
    - gdown
  commands:
    - gdown --help

about:
  home: https://github.com/wkentaro/gdown
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download a large file from Google Drive.
  description: |
    Download a large file from Google Drive.
    If you use curl/wget, it fails with a large file because of the security
    warning from Google Drive.

extra:
  recipe-maintainers:
    - hmaarrfk
