{% set name = "gdown" %}
{% set version = "4.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37edc3a0edda1a7fe5ebcc631c3aad0612582766460630ee52f481ba1ec7aefe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gdown = gdown.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - filelock
    - requests
    - six
    - tqdm
    - beautifulsoup4

test:
  imports:
    - gdown
  commands:
    - gdown --help

about:
  home: https://github.com/wkentaro/gdown
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download a large file from Google Drive.
  description: |
    Download a large file from Google Drive.
    If you use curl/wget, it fails with a large file because of the security
    warning from Google Drive.

extra:
  recipe-maintainers:
    - hmaarrfk
